<a href="https://colab.research.google.com/github/logeshpalanivel/TV_Marketing_Price_Prediction_Using_LinearRegression/blob/main/TV_Marketing_Price_Prediction_Using_LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("/content/tvmarketing.csv")

In [3]:
df.head()

TV  Sales
0  230.1   22.1
1   44.5   10.4
2   17.2    9.3
3  151.5   18.5
4  180.8   12.9

In [4]:
df.tail()

TV  Sales
195   38.2    7.6
196   94.2    9.7
197  177.0   12.8
198  283.6   25.5
199  232.1   13.4

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   TV      200 non-null    float64
 1   Sales   200 non-null    float64
dtypes: float64(2)
memory usage: 3.2 KB


In [6]:
df.shape

(200, 2)

In [7]:
df.describe()

TV       Sales
count  200.000000  200.000000
mean   147.042500   14.022500
std     85.854236    5.217457
min      0.700000    1.600000
25%     74.375000   10.375000
50%    149.750000   12.900000
75%    218.825000   17.400000
max    296.400000   27.000000

In [8]:
df.isnull().sum()

TV       0
Sales    0
dtype: int64

In [9]:
X = df['TV']
Y = df['Sales']

In [10]:
X.shape

(200,)

In [11]:
Y.shape

(200,)

In [12]:
X1 = X.values.reshape(X.values.size,1)

In [13]:
X1.shape

(200, 1)

In [14]:
from sklearn.linear_model import LinearRegression

In [15]:
le = LinearRegression()

In [16]:
le.fit(X1,Y)

LinearRegression()

In [17]:
le.score(X1,Y)

0.611875050850071

In [18]:
le.coef_

array([0.04753664])

In [19]:
le.intercept_

7.032593549127695

In [20]:
le.predict([[67.8]])

array([10.25557777])

In [21]:
le.predict([[50],[100]])

array([ 9.40942557, 11.78625759])